### ISSUE TITLE
Incorrect username when running `phase2cli auth`

### ISSUE THREAD

**Issue by etan-k** [privacy-scaling-explorations/p0tion#187]
# Expected Behavior

`phase2cli auth` should obtain the correct username.

# Current Behavior

`phase2cli` obtains an incorrect username, possibly an older one (?)

# Failure Information

When I run `phase2cli auth`, `phase2cli` reads my account name as `@etan` despite the account being named `@etan-k`. https://github.com/etan is a different, seemingly inactive, account and not owned by me.

## Steps to Reproduce

1. `phase2cli auth`
2. Enter auth code into device login form
3. Incorrect name is logged
4. Can't contribute to ceremonies because the account can't be found.

Unfortunately we could not find a user document with your information. This likely means that you did not pass the GitHub reputation checks and therefore are not elegible to contribute to any ceremony. If you believe you pass the requirements, it might be possible that your profile is private and we were not able to fetch your real statistics, in this case please consider making your profile public for the duration of the contribution. Please contact the coordinator if you believe this to be an error.

## Context

```
% phase2cli --version
1.0.8

% sw_vers
ProductName:		macOS
ProductVersion:		13.5.2
BuildVersion:		22G91o
```

## Failure Logs

```
   ___ _                      ____         _ _ 
  / _ \ |__   __ _ ___  ___  |___ \    ___| (_)
 / /_)/ '_ \ / _` / __|/ _ \   __) |  / __| | |
/ ___/| | | | (_| \__ \  __/  / __/  | (__| | |
\/    |_| |_|\__,_|___/\___| |_____|  \___|_|_|
                                               
Greetings, @etan 👋

⚠ The contribution process is based on a parallel waiting queue mechanism allowing one contributor at a time per circuit with a maximum time upper-bound. Each contribution may require the bulk of your computing resources and memory based on the size of the circuit (ETAs could vary!). If you stop your contribution at any step, you have to restart the step from scratch (except for uploading).

✖ Unfortunately we could not find a user document with your information. This likely means that you did not pass the GitHub reputation checks and therefore are not elegible to contribute to any ceremony. If you believe you pass the requirements, it might be possible that your profile is private and we were not able to fetch your real statistics, in this case please consider making your profile public for the duration of the contribution. Please contact the coordinator if you believe this to be an error.
```

**Comment by ctrlc03** [comment]
Hi @etan-k - sorry if it took this long to get back to you. 
I can see from your account (etan-k) that you are missing one of the requirements: follow 5 users (these are having 1 public repo, have 1 follower, and follow 5 users). 
As for seeing "Greetings, @etan" this is actually referring to your account, just it removed the "-" (we make a call to Github's api using the access token, which returns a handle in the form handle-id and seems like we did not consider that some usernames might be user-user-id, hence why you only see "etan").

**Comment by etan-k** [comment]
Thanks for the explanation. Seems like this is working as expected, then, and just a UI glitch.

It would be great if the requirements were actually part of the error message. The current one is a bit vague.

**Comment by ctrlc03** [comment]
You are totally right, it should be clearer - thanks for pointing it out. ps. you can try to contribute to ceremonies via https://ceremony.pse.dev - that's a bit more verbose when it comes to participation requirements. 
Please let me know if you get to contributing and have any issues I'll be happy to help you 🙂
