### ISSUE TITLE
Error: [ERROR] not-found: Unable to find a document with the given identifier for the provided collection path

### ISSUE THREAD

**Issue by gurrpi** [privacy-scaling-explorations/p0tion#189]
Received incident alert for `checkAndRemoveBlockingContributor` Cloud Function instance  Oct 11, 2023, 9:59:04 PM UTC. 

<img width="1500" alt="Screenshot 2023-10-12 at 10 20 20" src="https://github.com/privacy-scaling-explorations/p0tion/assets/1610146/5ead9ef2-21b9-4a34-9718-8f36d393e5f3">

severity: very low
environment: production
clound function: `checkAndRemoveBlockingContributor`
incident alert link: https://console.cloud.google.com/monitoring/alerting/incidents/0.n3a73tt8m8g8?authuser=3&project=pse-p0tion-production

### Former cases

It happended twice before:
<img width="1248" alt="Screenshot 2023-10-12 at 10 23 26" src="https://github.com/privacy-scaling-explorations/p0tion/assets/1610146/c076ce09-5b9c-417e-96e1-fda8b890e142">

**Comment by ctrlc03** [comment]
This was caused by a manual cleanup of a participant doc, which was not removed from the currentContributor field of the circuit, hence why the checkAndRemoveBlockingParticipant failed as there was no doc for this user in the participant collection.
