### ISSUE TITLE
CI: Failure of `Test Firebase Emulator` workflow

### ISSUE THREAD

**Issue by gurrpi** [privacy-scaling-explorations/p0tion#204]
Seems like EC2 instance had terminated in the middle of testing:
<img width="1487" alt="Screenshot 2023-10-20 at 14 26 56" src="https://github.com/privacy-scaling-explorations/p0tion/assets/1610146/8013baf6-4187-4257-a949-5b0f7e20b08f">

<img width="1462" alt="Screenshot 2023-10-20 at 14 27 04" src="https://github.com/privacy-scaling-explorations/p0tion/assets/1610146/20af45e7-fd65-4041-bd99-fbf0b8ba0a45">
https://github.com/privacy-scaling-explorations/p0tion/actions/runs/6575195204

**Comment by ctrlc03** [comment]
oh that was me terminating the instance on aws, my bad
