### ISSUE TITLE
Usernames with dashes get cut off

### ISSUE THREAD

**Issue by Divide-By-0** [privacy-scaling-explorations/p0tion#222]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

-   [y] I am running the latest version
-   [y] I checked the documentation and found no answer
-   [y] I checked to make sure that this issue has not already been filed

# Current Behavior

I get this message after authenticating:

√ You are authenticated as @Divide and now able to interact with zk-SNARK Phase2 Trusted Setup ceremonies

Even though my username is Divide-By-0. 

Edit: Used to be a UI bug. Now gives error when contributing.

**Comment by ctrlc03** [comment]
Thank you for taking the time open this issue, we will try and fix this as soon as we get a chance🙂

**Comment by citizen-stig** [comment]
Same

**Comment by glamperd** [comment]
Fixed in v1.2.5
