### ISSUE TITLE
I cannot finalize ZKP2P Trusted Setup Ceremony V2

### ISSUE THREAD

**Issue by nrs-minhdoan** [privacy-scaling-explorations/p0tion#249]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

-   [x] I am running the latest version
-   [x] I checked the documentation and found no answer
-   [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

I can finalize ZKP2P Trusted Setup Ceremony V2

# Current Behavior

I cannot finalize ZKP2P Trusted Setup Ceremony V2

# Failure Information

I cannot finalize ZKP2P Trusted Setup Ceremony V2 and my command show error.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

I just run command `phase2cli auth && phase2cli contribute -c zkp2p-trusted-setup-ceremony-v2`

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

- Platform: MacOS Sonoma 14.1.2
- Node version: v20.10.0
- phase2cli version: v1.1.0

## Failure Logs

`
🕛  Computing contribution... (ETA 00:00:03:09).
⚠ This may take longer or less time on your machine! Everything's fine, just be patient and do not stop the computation to avoid starting over again/Users/minhdoan/.nvm/versions/node/v20.10.0/lib/node_modules/@p0tion/phase2cli/node_modules/solc/soljson.js:133
    process["on"]("unhandledRejection", function (reason) { throw reason; });
                                                            ^

[Error: ENOENT: no such file or directory, open './output/contribute/zkeys/zkp2p-venmo-send-v2_00002.zkey'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './output/contribute/zkeys/zkp2p-venmo-send-v2_00002.zkey'
}
`

<img width="1630" alt="Screenshot 2024-01-08 at 14 41 00" src="https://github.com/privacy-scaling-explorations/p0tion/assets/57950156/562e9b8d-458b-4fdc-9766-54ce756128de">

**Comment by nvthaovn** [comment]
I also encountered the same problem

**Comment by glamperd** [comment]
Possible causes: - Ceremony begun on 1 machine, resumed on another; or environment cleaned, then ceremony resumed.

**Comment by glamperd** [comment]
To follow up, we would need the exact steps prior to this error.

**Comment by nrs-minhdoan** [comment]
@glamperd Yes,  I started the ceremony on a VPS then resumed on my Mac
