### ISSUE TITLE
Display active ceremonies first on the homepage

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/p0tion#267]
# Motivation

As a potential contributor, I want to see ceremonies that I'm able to contribute to displayed first

# Details

**On the homepage, list ceremonies in descending order based off their deadline, so that active ceremonies (ceremonies with deadlines in the future) are displayed on top**

Currently it seems ceremonies are listed randomly(?):
https://ceremony.pse.dev/

Despite [MACI V1.2.0 Trusted Setup Ceremony](https://ceremony.pse.dev/projects/MACI%20V1.2.0%20Trusted%20Setup%20Ceremony) being the ONLY active ceremony, it's listed 6th on the homepage:

![Image 2024-03-01 at 12 42 46](https://github.com/privacy-scaling-explorations/p0tion/assets/8097623/db2797df-9219-44e0-8e2c-97cad30a416a)

**Comment by glamperd** [comment]
Fix now live in DefinitelySetup
