### ISSUE TITLE
Wrong URL encoding in Twitter (X) post popup after ceremony.

### ISSUE THREAD

**Issue by kuzdogan** [privacy-scaling-explorations/p0tion#306]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

-   [ ] I am running the latest version (issue persists in 1.2.4)
-   [x] I checked the documentation and found no answer
-   [x] I checked to make sure that this issue has not already been filed

After running a ceremony the client pops-up a link to Twitter/X to initiate the user to share their contribution. However the popped up URL is not encoded correctly and does not resolve to a correct string:

```
https://x.com/intent/post?text=I%2520contributed%2520to%2520the%2520Semaphore+V4+Ceremony%21%2520You%2520can%2520view%2520the%2520steps%2520to%2520contribute%2520here%3A%2520https%3A%2F%2Fceremony.pse.dev%2520You%2520can%2520view%2520my%2520attestation%2520here%3A%2520https%3A%2F%2Fgist.github.com%2Fkuzdogan%2F3168f12bfb2e5786a831bc7db16b054a%2520
```

The screenshot:
<img width="737" alt="Screenshot 2024-06-11 at 09 46 25" src="https://github.com/privacy-scaling-explorations/p0tion/assets/13069972/bc703e05-b7a0-41a8-84ec-2f32ed075acd">

However the URL in the CLI output is correct:
```
ℹ We encourage you to tweet to spread the word about your participation to the ceremony by clicking the link below

https://twitter.com/intent/tweet?text=I%20contributed%20to%20the%20Semaphore V4 Ceremony!%20You%20can%20view%20the%20steps%20to%20contribute%20here:%20https://ceremony.pse.dev%20You%20can%20view%20my%20attestation%20here:%20https://gist.github.com/kuzdogan/3168f12bfb2e5786a831bc7db16b054a%20#Ethereum%20#ZKP

Thank you for participating and securing the Semaphore V4 Ceremony ceremony 🙏
```

## Steps to Reproduce

Initially observed this at the Semaphore V4 Ceremony. Same happened in the Anon Aadhaar V2 Trusted Setup Ceremony as well.

URL popup after Anon Aadhaar setup:
```
https://x.com/intent/post?text=I%2520contributed%2520to%2520the%2520Anon+Aadhaar+V2+Trusted+Setup+Ceremony%21%2520You%2520can%2520view%2520the%2520steps%2520to%2520contribute%2520here%3A%2520https%3A%2F%2Fceremony.pse.dev%2520You%2520can%2520view%2520my%2520attestation%2520here%3A%2520https%3A%2F%2Fgist.github.com%2Fkuzdogan%2F4dfe1fe5522cc2f84d609a3a546d1204%2520
```

<img width="756" alt="image" src="https://github.com/privacy-scaling-explorations/p0tion/assets/13069972/94704bc7-3140-4b0a-a742-25031ba41221">

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

-   Operating System: MacOS 14.4.1 
-   phase2cli version 1.2.3

**Comment by glamperd** [comment]
Looks like it's being re-encoded in the browser version. Investigating.

**Comment by glamperd** [comment]
Could be the issue referred to (and fixed) here: https://github.com/sindresorhus/open/pull/182

**Comment by glamperd** [comment]
Can't reproduce. 
Using Windows/Edge browser.
Click 'Attestation' > https://x.com/intent/post?text=I+contributed+to+the+local+test+Phase+2+Trusted+Setup+ceremony%21+You+can+view+the+steps+to+contribute+here%3A+https%3A%2F%2Fceremony.pse.dev+You+can+view+my+attestation+here%3A+https%3A%2F%2Fgist.github.com%2Fglamperd%2F7078b03bc1e2573eb5f8cdfb93e7d9e6+

... Which renders the tweet properly.
