### ISSUE TITLE
CLI package configuration

### ISSUE THREAD

**Issue by 0xjei** [privacy-scaling-explorations/p0tion#53]
To configure the `phase2cli` it turns out that it is necessary to manually copy the `.env` inside the `dist/` before publishing the package or use it with `npm link` locally. As a result, this process is tedious and easy to forget. Therefore, better to convert the environment to a `.json` file that is automatically included in the `dist/` during the build process.

**Comment by gurrpi** [comment]
Fixed in https://github.com/privacy-scaling-explorations/p0tion/pull/124
